CREATE TABLE IF NOT EXISTS {{table}} (
 matchup_key STRING NOT NULL COMMENT 'Chave direcional do confronto no formato matchup|ruleset|attacker_id|defender_id',
 ruleset_key STRING NOT NULL COMMENT 'Chave do ruleset aplicado ao cálculo do confronto',
 attacker_pokemon_key STRING NOT NULL COMMENT 'Chave canônica do Pokémon atacante',
 attacker_pokemon_id BIGINT NOT NULL COMMENT 'Identificador PokéAPI do Pokémon atacante',
 defender_pokemon_key STRING NOT NULL COMMENT 'Chave canônica do Pokémon defensor',
 defender_pokemon_id BIGINT NOT NULL COMMENT 'Identificador PokéAPI do Pokémon defensor',
 attacker_best_move_key STRING NOT NULL COMMENT 'Chave do melhor movimento de dano selecionado para o atacante',
 attacker_best_move_name STRING NOT NULL COMMENT 'Nome em inglês do melhor movimento selecionado para o atacante',
 attacker_type_multiplier DOUBLE NOT NULL COMMENT 'Multiplicador de efetividade do movimento atacante contra os tipos do defensor',
 attacker_stab_multiplier DOUBLE NOT NULL COMMENT 'Multiplicador STAB do atacante; 1.5 quando o movimento compartilha tipo com o Pokémon',
 attacker_expected_damage DECIMAL(10,2) NOT NULL COMMENT 'Dano esperado arredondado do atacante no baseline determinístico',
 attacker_damage_pct DECIMAL(10,2) NOT NULL COMMENT 'Percentual do HP do defensor removido pelo dano esperado do atacante',
 attacker_turns_to_ko INT NOT NULL COMMENT 'Turnos estimados para o atacante nocautear o defensor; 999 quando não causa dano',
 defender_best_move_key STRING NOT NULL COMMENT 'Chave do melhor movimento de dano selecionado para o defensor',
 defender_best_move_name STRING NOT NULL COMMENT 'Nome em inglês do melhor movimento selecionado para o defensor',
 defender_type_multiplier DOUBLE NOT NULL COMMENT 'Multiplicador de efetividade do movimento defensor contra os tipos do atacante',
 defender_stab_multiplier DOUBLE NOT NULL COMMENT 'Multiplicador STAB do defensor; 1.5 quando o movimento compartilha tipo com o Pokémon',
 defender_expected_damage DECIMAL(10,2) NOT NULL COMMENT 'Dano esperado arredondado do defensor no baseline determinístico',
 defender_damage_pct DECIMAL(10,2) NOT NULL COMMENT 'Percentual do HP do atacante removido pelo dano esperado do defensor',
 defender_turns_to_ko INT NOT NULL COMMENT 'Turnos estimados para o defensor nocautear o atacante; 999 quando não causa dano',
 attacker_moves_first BOOLEAN NOT NULL COMMENT 'Indica se o atacante age primeiro por prioridade e velocidade no baseline',
 matchup_score DECIMAL(10,2) NOT NULL COMMENT 'Score determinístico do confronto combinando turnos para KO, dano percentual e iniciativa',
 attacker_win_probability DECIMAL(4,2) NOT NULL COMMENT 'Probabilidade sintética do atacante vencer, derivada por transformação logística do score',
 predicted_winner_key STRING NOT NULL COMMENT 'Chave do Pokémon previsto como vencedor no baseline determinístico',
 prediction_reason STRING NOT NULL COMMENT 'Justificativa auditável com melhor movimento, efetividade, turnos e imunidades',
 gold_transformed_at TIMESTAMP NOT NULL COMMENT 'Momento horário de Brasília (UTC-3) da publicação Gold',
 gold_run_id STRING NOT NULL COMMENT 'UUID da execução Gold responsável pela publicação'
) USING DELTA CLUSTER BY (attacker_pokemon_id,defender_pokemon_id)
COMMENT 'Baseline determinístico direcional de confrontos Scarlet/Violet singles nível 50'
